package server

import (
	"fmt"
	"net/http"
	"strconv"
	"strings"
	"time"
)

// The demo page is a stable practice target for learning search patterns:
// no network access needed, and one new "article" appears each day so a
// feed built against it visibly updates.

var demoTopics = []string{
	"CSS finally gets masonry layout",
	"JavaScript runtime written in a weekend",
	"The return of server-side rendering",
	"Why RSS never really died",
	"Vocational students ship production apps",
	"A tiny web server in 100 lines of Go",
	"Browser devtools tricks nobody taught you",
	"Static sites are having a moment again",
}

type demoArticle struct {
	N       int
	Title   string
	Date    string
	Summary string
}

func demoArticles(now time.Time) []demoArticle {
	articles := make([]demoArticle, 0, 6)
	for i := 0; i < 6; i++ {
		day := now.AddDate(0, 0, -i)
		topic := demoTopics[day.YearDay()%len(demoTopics)]
		articles = append(articles, demoArticle{
			N:       day.Year()*1000 + day.YearDay(),
			Title:   topic,
			Date:    day.Format("2006-01-02"),
			Summary: fmt.Sprintf("A short summary of “%s”, published on %s. Use the patterns from the README to turn this list into a feed.", topic, day.Format("January 2, 2006")),
		})
	}
	return articles
}

func demoHTML(now time.Time) string {
	var sb strings.Builder
	sb.WriteString(`<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><title>FeedForge Demo News</title></head>
<body>
<h1>FeedForge Demo News</h1>
<p>This page exists so you can practice writing search patterns. A new article appears every day.</p>
<h2>Latest Articles</h2>
<ul class="articles">
`)
	for _, a := range demoArticles(now) {
		fmt.Fprintf(&sb, `  <li class="article">
    <a href="/demo/article/%d">%s</a>
    <span class="date">%s</span>
    <p class="summary">%s</p>
  </li>
`, a.N, a.Title, a.Date, a.Summary)
	}
	sb.WriteString(`</ul>
<footer>Generated by FeedForge — the demo page.</footer>
</body>
</html>
`)
	return sb.String()
}

func (s *Server) handleDemo(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	fmt.Fprint(w, demoHTML(time.Now()))
}

func (s *Server) handleDemoArticle(w http.ResponseWriter, r *http.Request) {
	n, err := strconv.Atoi(r.PathValue("n"))
	if err != nil {
		http.NotFound(w, r)
		return
	}
	for _, a := range demoArticles(time.Now()) {
		if a.N == n {
			w.Header().Set("Content-Type", "text/html; charset=utf-8")
			fmt.Fprintf(w, `<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><title>%s — FeedForge Demo</title></head>
<body>
<h1>%s</h1>
<p><em>%s</em></p>
<p>%s</p>
<p><a href="/demo">← Back to the article list</a></p>
</body>
</html>
`, a.Title, a.Title, a.Date, a.Summary)
			return
		}
	}
	http.NotFound(w, r)
}
