package server

import (
	"net/http"

	"github.com/real-jiakai/feedforge/internal/store"
)

// A Recipe is a ready-made feed definition for a site that has no feed of
// its own. Picking one in the wizard fills in every field, so the patterns
// can be inspected and tweaked rather than taken on faith.
//
// Each recipe is exercised against a saved copy of its target page in
// recipes_test.go, so a silent breakage shows up as a failing test rather
// than as an empty feed.
type Recipe struct {
	ID     string     `json:"id"`
	Name   string     `json:"name"`
	Note   string     `json:"note"`
	NoteZH string     `json:"noteZh"`
	Feed   store.Feed `json:"feed"`
}

// Recipes are ordered from simplest to most instructive.
var Recipes = []Recipe{
	{
		ID:     "demo",
		Name:   "FeedForge demo page",
		Note:   "The built-in practice page. A new article appears every day.",
		NoteZH: "内置练习页面，每天出现一篇新文章。",
		Feed: store.Feed{
			Title:       "FeedForge Demo News",
			Description: "Practice feed generated from the built-in demo page",
			SourceURL:   store.DemoSourceURL,
			// The demo page is generated by this server, so its markup is
			// stable and the pattern can be written plainly.
			GlobalPattern: `<ul class="articles">{%}</ul>`,
			ItemPattern: `<li class="article">{*}<a href="{%}">{%}</a>{*}` +
				`<span class="date">{%}</span>{*}<p class="summary">{%}</p>`,
			ItemTitle:       "{%2}",
			ItemLink:        "{%1}",
			ItemContent:     "<p>{%4}</p><p><em>{%3}</em></p>",
			SmartWhitespace: true,
			MaxItems:        25,
			TTLMinutes:      30,
		},
	},
	{
		ID:     "hackernews",
		Name:   "Hacker News front page",
		Note:   "Shows how little is needed: one line captures every headline and link.",
		NoteZH: "展示最简单的写法：一行模式就能抓到所有标题和链接。",
		Feed: store.Feed{
			Title:           "Hacker News Front Page",
			Link:            "https://news.ycombinator.com/",
			Description:     "Front page stories from Hacker News",
			SourceURL:       "https://news.ycombinator.com/",
			ItemPattern:     `<span class="titleline"><a href="{%}">{%}</a>`,
			ItemTitle:       "{%2}",
			ItemLink:        "{%1}",
			SmartWhitespace: true,
			MaxItems:        30,
			TTLMinutes:      30,
		},
	},
	{
		ID:     "ossinsight",
		Name:   "OSSInsight blog",
		Note:   "Each post is one <a> wrapping an <article>. {*} skips the long Tailwind class lists.",
		NoteZH: "每篇文章都是一个 <a> 包住 <article>。用 {*} 跳过冗长的 Tailwind 类名。",
		Feed: store.Feed{
			Title:       "OSSInsight Blog",
			Link:        "https://ossinsight.io/blog",
			Description: "Data-driven open source insights from OSSInsight",
			SourceURL:   "https://ossinsight.io/blog",
			// The h2 class differs between the featured post and the grid
			// posts, so the class value is skipped rather than matched.
			ItemPattern:     `<a class="group block" href="{%}">{*}<time>{%}</time>{*}<h2 class="{*}>{%}</h2>`,
			ItemTitle:       "{%3}",
			ItemLink:        "{%1}",
			ItemContent:     "<p>{%3}</p><p><em>{%2}</em></p>",
			SmartWhitespace: true,
			MaxItems:        30,
			TTLMinutes:      60,
		},
	},
	{
		ID:   "bytes",
		Name: "Bytes.dev archives",
		Note: "The newest issue uses different markup from the rest of the list — " +
			"the pattern stays loose enough to catch both.",
		NoteZH: "最新一期的 HTML 结构和列表里的其他条目不同 —— 模式写得足够宽松，两种都能匹配。",
		Feed: store.Feed{
			Title:       "Bytes — JavaScript Newsletter",
			Link:        "https://bytes.dev/archives",
			Description: "Every issue of the Bytes JavaScript newsletter",
			SourceURL:   "https://bytes.dev/archives",
			// Anchored on the issue href and the shared "grid gap-2" wrapper.
			// The date span's weight class (font-bold vs font-semibold) and
			// the title's tag (<p> vs <div>) both vary, so both are skipped.
			ItemPattern: `href="/archives/{%}">{*}<div class="grid gap-2">` +
				`<span class="font-{*}>{%}</span><h3{*}Issue <!-- -->{%}</span><{*}>{%}</`,
			ItemTitle:       "Issue {%3}: {%4}",
			ItemLink:        "/archives/{%1}",
			ItemContent:     "<p>{%4}</p><p><em>Issue {%3} · {%2}</em></p>",
			SmartWhitespace: true,
			MaxItems:        30,
			TTLMinutes:      60,
		},
	},
}

func (s *Server) handleRecipes(w http.ResponseWriter, r *http.Request) {
	writeJSON(w, http.StatusOK, Recipes)
}
